services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dating
      POSTGRES_PASSWORD: dating
      POSTGRES_DB: dating
    ports:
      - '5422:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data:
